# Generated by Django 3.2.4 on 2021-06-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping_label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('order_status', models.TextField(max_length=16)),
                ('item', models.TextField(max_length=40)),
                ('price', models.TextField(max_length=30)),
                ('bought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping_label.shipping_data')),
            ],
        ),
    ]
