# Generated by Django 3.2.4 on 2021-06-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='bought_by',
            field=models.CharField(max_length=30),
        ),
    ]
