# Generated by Django 3.2.4 on 2021-06-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_status', '0003_alter_orderstatus_bought_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['order_number']},
        ),
    ]
