# Generated by Django 3.2.4 on 2021-06-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status', '0006_alter_orderstatus_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
