# Generated by Django 3.2.4 on 2021-06-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status', '0022_alter_orderstatus_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order_number',
            field=models.CharField(max_length=5),
        ),
    ]
