# Generated by Django 3.2.4 on 2021-06-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
